### ISSUE TITLE
XProtoNet  o de

### ISSUE THREAD

**Issue by Chardqui** [ejkim47/prob-cbm#2]
Hi! Do you have the XProtoNet Code? I’m starting my PhD and I want to study it for my research

**Comment by ejkim47** [comment]
Thank you for your interest in my research.

I have not published the XProtoNet code repository.
However, most of the code is written based on ProtoPNet public code (https://github.com/cfchen-duke/ProtoPNet).

I will close it because it does not correspond to this git repository.
