### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/class_attr_data_10/attributes.txt'

### ISSUE THREAD

**Issue by Adasunnylily** [ejkim47/prob-cbm#3]
hi, great work! 
I am confused about the CUB data '/class_attr_data_10/attributes.txt', which cannot be found in the url provided, but required in the code, Could you please provide the full cub dataset that needed to reproduce results?
Thank you so much！

**Comment by Adasunnylily** [comment]
and also the train.pkl 、val.pkl and test.pkl

**Comment by ejkim47** [comment]
Thank you for your interest!

As mentioned in the ReadMe, please follow the instructions at https://github.com/yewsiang/ConceptBottleneck/tree/master/CUB.
They provide all the necessary data files.
I'll go ahead and close this issue.

Thanks!
